### ISSUE TITLE
Orchestra Startup issue

### ISSUE THREAD

**Issue by lalith-chennupati** [OpenUnison/openunison-k8s-activedirectory#16]
Getting the following exception after installing orchestra:

[2020-06-18 18:04:16,616][main] INFO  OpenUnisonOnUndertow - OpenUnison XML File : '/usr/local/openunison/work/webapp/WEB-INF/unison.xml'
[2020-06-18 18:04:16,626][main] INFO  OpenUnisonConfigLoader - No config from include files, using original
[2020-06-18 18:04:16,979][main] INFO  OpenUnisonOnUndertow - Loading keystore : '/etc/openunison/unisonKeyStore.p12'
[2020-06-18 18:04:16,979][main] INFO  OpenUnisonOnUndertow - Building Undertow
[2020-06-18 18:04:16,994][main] INFO  OpenUnisonOnUndertow - Check if enabling HTTP2 - false
[2020-06-18 18:04:16,994][main] INFO  OpenUnisonOnUndertow - Enabling HTTP2
[2020-06-18 18:04:16,996][main] INFO  OpenUnisonOnUndertow - Adding open port : '8080'
[2020-06-18 18:04:17,484][main] INFO  OpenUnisonOnUndertow - NOT Supporting TLS Protocol : 'SSLv2Hello'
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - NOT Supporting TLS Protocol : 'TLSv1'
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - NOT Supporting TLS Protocol : 'TLSv1.1'
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - Supporting TLS Protocol : 'TLSv1.2'
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - Configured TLS Listener on Port 8443
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - Path to webapp : '/usr/local/openunison/work/webapp'
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - Path directory? : 'true'
[2020-06-18 18:04:17,485][main] INFO  OpenUnisonOnUndertow - Path exists : 'true'
[2020-06-18 18:04:18,020][main] INFO  OpenUnisonServletFilter - Loading environment file : '/etc/openunison/ou.env'
[2020-06-18 18:04:18,020][main] INFO  OpenUnisonServletFilter - Adding property : 'GITHUB_CLIENT_ID'
[2020-06-18 18:04:18,021][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_DASHBOARD_NAMESPACE'
[2020-06-18 18:04:18,021][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_DB_SECRET'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_URL'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'MYVD_CONFIG_PATH'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'OU_HOST'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_CLUSTER_NAME'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_API_HOST'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_DASHBOARD_HOST'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'GITHUB_TEAMS'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'OU_QUARTZ_MASK'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'PROMETHEUS_SERVICE_ACCOUNT'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'SESSION_INACTIVITY_TIMEOUT_SECONDS'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_SELF_LINK'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'K8S_IMPERSONATION'
[2020-06-18 18:04:18,022][main] INFO  OpenUnisonServletFilter - Adding property : 'unisonKeystorePassword'
[2020-06-18 18:04:18,025][main] WARN  OpenUnisonServletFilter - No context paths present, assuming the config path is WEB-INF/unison.xml
[2020-06-18 18:04:18,025][main] INFO  OpenUnisonServletFilter - Initializing OpenUnison 1.0.18-2020042301
[2020-06-18 18:04:18,025][main] INFO  OpenUnisonServletFilter - Unison Configuration File : 'WEB-INF/unison.xml'
[2020-06-18 18:04:18,030][main] INFO  OpenUnisonConfigLoader - No config from include env, using original
[2020-06-18 18:04:18,031][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.forceToSSL='true'
[2020-06-18 18:04:18,031][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.openPort='8080'
[2020-06-18 18:04:18,031][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.securePort='8443'
[2020-06-18 18:04:18,031][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.externalOpenPort='80'
[2020-06-18 18:04:18,031][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.externalSecurePort='443'
[2020-06-18 18:04:18,036][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.activemqdir='/tmp/amq'
[2020-06-18 18:04:18,036][main] INFO  OpenUnisonConfigManager - Loading configuration - com.tremolosecurity.openunison.quartzdir='/tmp/quartz'
[2020-06-18 18:04:18,068][main] INFO  OpenUnisonConfigLoader - No config from include files, using original
[2020-06-18 18:04:18,085][main] INFO  OpenUnisonConfigManager - Removing node : [filter: null] - [param: null]
[2020-06-18 18:04:18,088][main] INFO  OpenUnisonConfigManager - Removing node : [results: null] - [azSuccess: null]
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.configure(LDAPInterceptor.java:107)
	at net.sourceforge.myvd.core.InsertChain.configureChain(InsertChain.java:192)
	at net.sourceforge.myvd.server.ServerCore.configureChain(ServerCore.java:72)
	at net.sourceforge.myvd.server.ServerCore.buildNamespaces(ServerCore.java:134)
	at net.sourceforge.myvd.server.ServerCore.startService(ServerCore.java:150)
	at com.tremolosecurity.openunison.OpenUnisonConfigManager.loadMyVD(OpenUnisonConfigManager.java:348)
	at com.tremolosecurity.config.util.UnisonConfigManagerImpl.initialize(UnisonConfigManagerImpl.java:372)
	at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:351)
	at com.tremolosecurity.openunison.OpenUnisonServletFilter.init(OpenUnisonServletFilter.java:118)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:591)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:329)
Exception in thread "main" javax.servlet.ServletException: java.lang.NumberFormatException: For input string: ""
	at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:382)
	at com.tremolosecurity.openunison.OpenUnisonServletFilter.init(OpenUnisonServletFilter.java:118)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:591)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:329)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.configure(LDAPInterceptor.java:107)
	at net.sourceforge.myvd.core.InsertChain.configureChain(InsertChain.java:192)
	at net.sourceforge.myvd.server.ServerCore.configureChain(ServerCore.java:72)
	at net.sourceforge.myvd.server.ServerCore.buildNamespaces(ServerCore.java:134)
	at net.sourceforge.myvd.server.ServerCore.startService(ServerCore.java:150)
	at com.tremolosecurity.openunison.OpenUnisonConfigManager.loadMyVD(OpenUnisonConfigManager.java:348)
	at com.tremolosecurity.config.util.UnisonConfigManagerImpl.initialize(UnisonConfigManagerImpl.java:372)
	at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:351)
	... 9 more

**Comment by mlbiam** [comment]
in your CR (`kubectl edit openunison orchestra -n openunison`) look for `AD_PORT` in `spec.non_secret_data`.  It's likely blank.  You need to set the port for AD (usually 636)
